spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/test
        username: root
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: 
                        client-secret:
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        client-name: Kakao
                        scope:
                            - profile_image
                            - profile_nickname
                            - account_email
                    naver:
                        client-id: 
                        client-secret: 
                        redirect-uri:  http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        scope:
                            - name
                            - email
                    google:
                        client-id: 
                        client-secret: 
                        scope:
                            - profile
                            - email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
    jpa:
        hibernate:
            ddl-auto: update